# Generated by Django 4.2.10 on 2024-10-10 00:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainigRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Оценка не может быть меньше 1'), django.core.validators.MaxValueValidator(5, message='Оценка не может быть больше 5')], verbose_name='Желаемая оценка сотрудника')),
                ('ticket_source', models.CharField(choices=[('worker', 'Работник'), ('HR', 'HR'), ('regular', 'Регулярная'), ('manager', 'Руководитель')], max_length=20, verbose_name='Тикет откуда')),
                ('start_date', models.DateField(verbose_name='Дата начала обучения')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания обучения')),
                ('note', models.CharField(max_length=255, verbose_name='Заметка')),
                ('status', models.CharField(choices=[('on_discussion', 'на согласовании'), ('approved', 'одобрено'), ('cancellation', 'отмена'), ('denied', 'отказано'), ('in_process', 'в процессе')], max_length=20, verbose_name='Статус')),
                ('actual_hours', models.PositiveSmallIntegerField(verbose_name='Часов по факту')),
                ('planned_hours', models.PositiveSmallIntegerField(verbose_name='Запланированные часы')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Сотрудник')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.skill', verbose_name='Навык')),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='PositionRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Оценка не может быть меньше 1'), django.core.validators.MaxValueValidator(5, message='Оценка не может быть больше 5')], verbose_name='Эталонная оценка')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements_grade', to='employees.grade', verbose_name='Грейд')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements_position', to='employees.position', verbose_name='Должность')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='skills.skill', verbose_name='Скилл')),
            ],
            options={
                'verbose_name': 'Требования к позиции',
                'verbose_name_plural': 'Требования к позиции',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Добавлено')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Оценка не может быть меньше 1'), django.core.validators.MaxValueValidator(5, message='Оценка не может быть больше 5')], verbose_name='Эталонная оценка')),
                ('level_score', models.CharField(choices=[('Начинающий', 'Начинающий'), ('Базовый', 'Базовый'), ('Уверенный', 'Уверенный'), ('Экспертный', 'Экспертный')], max_length=20, verbose_name='Оценка на словах')),
                ('accordance', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет'), ('Не требуется', 'Не требуется')], max_length=20, verbose_name='Соответствие')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='employees.employee', verbose_name='сотрудник')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.skill', verbose_name='Скилл')),
            ],
        ),
    ]
