# Generated by Django 4.2.10 on 2024-10-10 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainigrequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_requests', to='employees.employee', verbose_name='Сотрудник'),
        ),
    ]
