# Generated by Django 4.2.10 on 2024-10-10 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('trainings', '0002_alter_trainigrequest_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentPlanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Сотрудник')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.grade', verbose_name='Грейд')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Заявка на план развития',
                'verbose_name_plural': 'Заявки на план развития',
                'ordering': ('pk',),
                'default_related_name': 'development_requests',
            },
        ),
    ]
