# Generated by Django 4.2.10 on 2024-10-10 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0003_developmentplanrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developmentplanrequest',
            options={'default_related_name': 'development_requests', 'ordering': ('pk',), 'verbose_name': 'Заявка на план развития', 'verbose_name_plural': 'Заявки на планы развитий'},
        ),
    ]
