version: '3'

volumes:
  pg_data_superstars:
  static_superstars:
  media_superstars:
    
services:

  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_superstars:/var/lib/postgresql/data

  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static_superstars:/backend_static
      - media_superstars:/media
    depends_on:
      - db


  frontend:
    image: annakharatova/super-stars
    # build: ./frontend/
    # build: ./frontend_spare/
    env_file: .env
    # build:
    #   context: ./frontend
    #   dockerfile: Dockerfile
    # command: cp -r /app/build/. /frontend_static/
    command: cp -r /app/dist/. /static/
    # command: cp -r /app/build/. /static/
    volumes:
      - static_superstars:/static


  gateway:
    # image: nginx:1.19.3
    build: ./gateway/
    env_file: .env
    ports:
      # - "8080:80"
      - 8080:80
      # - 8000:80
    volumes:
      # - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./frontend/build:/usr/share/nginx/html/
      # - ./docs/:/usr/share/nginx/html/api/docs/
      - static_superstars:/static
      # - media:/media
      - media_superstars:/media/employees/images/
    depends_on:
      - backend
      # - frontend
