# Generated by Django 4.2.10 on 2024-10-04 11:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('type', models.CharField(choices=[('Soft skills', 'Soft skills'), ('Hard skills', 'Hard skills')], max_length=11, verbose_name='Тип скилла')),
            ],
            options={
                'verbose_name': 'Компетенция',
                'verbose_name_plural': 'Компетенции',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Фамилия Имя')),
                ('bus_factor', models.BooleanField(default=False, verbose_name='Автобусный фактор')),
                ('created', models.DateField(verbose_name='Добавлено')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('Junior', 'Junior'), ('Middle', 'Middle'), ('Senior', 'Senior')], max_length=20)),
            ],
            options={
                'verbose_name': 'Домен',
                'verbose_name_plural': 'Домены',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='employees.competence', verbose_name='Компетенция')),
            ],
            options={
                'verbose_name': 'Скилл',
                'verbose_name_plural': 'Скиллы',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='TrainigRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(1, message='Оценка не может быть меньше 1'), django.core.validators.MinValueValidator(5, message='Оценка не может быть больше 5')], verbose_name='Желаемая оценка сотрудника')),
                ('ticket_source', models.CharField(choices=[('worker', 'Работник'), ('HR', 'HR'), ('regular', 'Регулярная'), ('manager', 'Руководитель')], max_length=20, verbose_name='Тикет откуда')),
                ('start_date', models.DateField(verbose_name='Дата начала обучения')),
                ('end_date', models.DateField(verbose_name='Дата окончания обучения')),
                ('note', models.CharField(max_length=255, verbose_name='Заметка')),
                ('status', models.CharField(choices=[('on_discussion', 'на согласовании'), ('approved', 'одобрено'), ('cancellation', 'отмена'), ('in_process', 'в процессе')], max_length=20, verbose_name='Статус')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Сотрудник')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.skill', verbose_name='Навык')),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Сотрудник')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.grade', verbose_name='Грейд')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Карьерная цель',
                'verbose_name_plural': 'Карьерные цели',
            },
        ),
        migrations.CreateModel(
            name='PositionRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(1, message='Оценка не может быть меньше 1'), django.core.validators.MinValueValidator(5, message='Оценка не может быть больше 5')], verbose_name='Эталонная оценка')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.grade', verbose_name='Грейд')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.position', verbose_name='Должность')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.skill', verbose_name='Скилл')),
            ],
            options={
                'verbose_name': 'Требования к позиции',
                'verbose_name_plural': 'Требования к позиции',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Добавлено')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(1, message='Оценка не может быть меньше 1'), django.core.validators.MinValueValidator(5, message='Оценка не может быть больше 5')], verbose_name='Эталонная оценка')),
                ('name', models.CharField(choices=[('Начинающий', 'Начинающий'), ('Базовый', 'Базовый'), ('Уверенный', 'Уверенный'), ('Экспертный', 'Экспертный')], max_length=20, verbose_name='Оценка на словах')),
                ('accordance', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет'), ('Не требуется', 'Не требуется')], max_length=20, verbose_name='Соответствие')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='сотрудник')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.skill', verbose_name='Скилл')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.grade', verbose_name='Грейд'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.position', verbose_name='Дожность'),
        ),
        migrations.AddField(
            model_name='employee',
            name='team',
            field=models.ManyToManyField(to='employees.team', verbose_name='Команды'),
        ),
    ]
