# Generated by Django 4.2.10 on 2024-10-10 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='employees/images/', verbose_name='Изображение'),
        ),
    ]
