# Generated by Django 4.2.10 on 2024-10-09 18:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Оценка не может быть меньше 1'), django.core.validators.MaxValueValidator(5, message='Оценка не может быть больше 5')], verbose_name='Эталонная оценка')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements_grade', to='employees.grade', verbose_name='Грейд')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements_position', to='employees.position', verbose_name='Должность')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='employees.skill', verbose_name='Скилл')),
            ],
            options={
                'verbose_name': 'Требования к позиции',
                'verbose_name_plural': 'Требования к позиции',
            },
        ),
    ]
