# Generated by Django 4.2.10 on 2024-10-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_trainigrequest_actual_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainigrequest',
            name='status',
            field=models.CharField(choices=[('on_discussion', 'на согласовании'), ('approved', 'одобрено'), ('cancellation', 'отмена'), ('denied', 'отказано'), ('in_process', 'в процессе')], max_length=20, verbose_name='Статус'),
        ),
    ]
