# Generated by Django 4.2.10 on 2024-10-05 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_trainigrequest_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='name',
            new_name='level_score',
        ),
    ]
