# Generated by Django 4.2.10 on 2024-10-05 22:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_trainigrequest_desired_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Оценка не может быть меньше 1'), django.core.validators.MaxValueValidator(5, message='Оценка не может быть больше 5')], verbose_name='Эталонная оценка'),
        ),
        migrations.AlterField(
            model_name='positionrequirement',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Оценка не может быть меньше 1'), django.core.validators.MaxValueValidator(5, message='Оценка не может быть больше 5')], verbose_name='Эталонная оценка'),
        ),
    ]
