# Generated by Django 4.2.10 on 2024-10-05 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_level_score_alter_positionrequirement_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='employees.employee', verbose_name='сотрудник'),
        ),
    ]
