# Generated by Django 4.2.10 on 2024-10-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_level_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='team',
            field=models.ManyToManyField(related_name='employees', to='employees.team', verbose_name='Команды'),
        ),
    ]
