# Generated by Django 4.2.10 on 2024-10-06 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_alter_positionrequirement_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionrequirement',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements_grade', to='employees.grade', verbose_name='Грейд'),
        ),
        migrations.AlterField(
            model_name='positionrequirement',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements_position', to='employees.position', verbose_name='Должность'),
        ),
    ]
